// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useState, useEffect, useRef, useCallback, useId, Fragment } from 'react';
import React from 'react';
import * as React_7214d18997ee864dd178de7b3a8430f6783e8b89 from 'react';
import { useSitecore, Text, Link, Placeholder, RichText, NextImage, withDatasourceCheck, Image, CdpHelper, DateField } from '@sitecore-content-sdk/nextjs';
import { VideoPlayer } from 'src/components/video/VideoPlayer.dev';
import { VideoModal } from 'src/components/video/VideoModal.dev';
import { useVideoModal } from 'src/hooks/useVideoModal';
import { useVideo } from '@/contexts/VideoContext';
import { Default } from 'components/icon/Icon';
import { Default as Default_e49b8b0315b5c2e1dfc6d29366b41ef250099b77 } from 'src/components/image/ImageWrapper.dev';
import { motion, AnimatePresence } from 'framer-motion';
import { isMobile } from '@/utils/isMobile';
import { extractVideoId } from '@/utils/video';
import { NoDataFallback } from '@/utils/NoDataFallback';
import { cn, getYouTubeThumbnail } from 'lib/utils';
import { Default as Default_2136db61e8a24a8a1d9ace0ce9528745ef345ee3 } from 'components/image/ImageWrapper.dev';
import { EditableButton, EditableImageButton } from 'components/button-component/ButtonComponent';
import * as TooltipPrimitive from '@radix-ui/react-tooltip';
import * as TogglePrimitive from '@radix-ui/react-toggle';
import { cva } from 'class-variance-authority';
import * as ToggleGroupPrimitive from '@radix-ui/react-toggle-group';
import { toggleVariants } from 'components/ui/toggle';
import { useToast } from '@/hooks/use-toast';
import { Toast, ToastClose, ToastDescription, ToastProvider, ToastTitle, ToastViewport } from 'components/ui/toast';
import * as ToastPrimitives from '@radix-ui/react-toast';
import { X, PanelLeft, Check, ChevronDown, ChevronUp, GripVertical, Circle, ChevronLeft, ChevronRight, MoreHorizontal, Dot, Search, ArrowLeft, ArrowRight, Play, Pause, Menu, Facebook, Linkedin, Twitter, Link as Link_6b289e2de0a07a8bed65fcf19e83723e986797b2, Mail } from 'lucide-react';
import * as TabsPrimitive from '@radix-ui/react-tabs';
import * as SwitchPrimitives from '@radix-ui/react-switch';
import { useTheme } from 'next-themes';
import { Toaster } from 'sonner';
import * as SliderPrimitive from '@radix-ui/react-slider';
import { Slot } from '@radix-ui/react-slot';
import { useIsMobile } from '@/hooks/use-mobile';
import { Button, buttonVariants } from 'components/ui/button';
import { Input } from 'components/ui/input';
import { Separator } from 'components/ui/separator';
import { Sheet, SheetContent, SheetTrigger } from 'components/ui/sheet';
import { Skeleton } from 'components/ui/skeleton';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from 'components/ui/tooltip';
import * as SheetPrimitive from '@radix-ui/react-dialog';
import * as SeparatorPrimitive from '@radix-ui/react-separator';
import * as SelectPrimitive from '@radix-ui/react-select';
import * as ScrollAreaPrimitive from '@radix-ui/react-scroll-area';
import * as ResizablePrimitive from 'react-resizable-panels';
import * as RadioGroupPrimitive from '@radix-ui/react-radio-group';
import * as ProgressPrimitive from '@radix-ui/react-progress';
import * as PopoverPrimitive from '@radix-ui/react-popover';
import * as NavigationMenuPrimitive from '@radix-ui/react-navigation-menu';
import * as MenubarPrimitive from '@radix-ui/react-menubar';
import * as LabelPrimitive from '@radix-ui/react-label';
import { OTPInput, OTPInputContext } from 'input-otp';
import * as HoverCardPrimitive from '@radix-ui/react-hover-card';
import { Controller, FormProvider, useFormContext, useForm } from 'react-hook-form';
import { Label } from 'components/ui/label';
import * as DropdownMenuPrimitive from '@radix-ui/react-dropdown-menu';
import { Drawer } from 'vaul';
import * as ContextMenuPrimitive from '@radix-ui/react-context-menu';
import { Command } from 'cmdk';
import { Dialog, DialogContent } from 'components/ui/dialog';
import * as CollapsiblePrimitive from '@radix-ui/react-collapsible';
import * as CheckboxPrimitive from '@radix-ui/react-checkbox';
import * as RechartsPrimitive from 'recharts';
import useEmblaCarousel from 'embla-carousel-react';
import { DayPicker } from 'react-day-picker';
import * as AvatarPrimitive from '@radix-ui/react-avatar';
import * as AspectRatioPrimitive from '@radix-ui/react-aspect-ratio';
import * as AlertDialogPrimitive from '@radix-ui/react-alert-dialog';
import * as AccordionPrimitive from '@radix-ui/react-accordion';
import { Meteors } from 'components/magicui/meteors';
import { TopicItem } from 'src/components/topic-listing/TopicItem.dev';
import { Default as Default_9c943e7f61c2c6a8bdaf3a4e8f1aeba5a19a6639 } from 'src/components/text-banner/TextBannerDefault.dev';
import { Default as Default_b7b9c2d49612cce49665fcafdf4020a775dae9a6 } from 'src/components/text-banner/TextBanner01.dev';
import { Default as Default_d90c163300dcab5740e1badcbbe8ffad62e34ea5 } from 'src/components/text-banner/TextBanner02.dev';
import { debounce } from 'radash';
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from 'components/ui/carousel';
import { Default as Default_f14713561e7127543a30e797b8ea6464ba634f1f } from 'src/components/testimonial-carousel/TestimonialCarouselItem';
import { Form, FormControl, FormField, FormItem, FormMessage } from 'components/ui/form';
import { useI18n } from 'next-localization';
import { dictionaryKeys } from '@/variables/dictionary';
import Head from 'next/head';
import NextLink from 'next/link';
import { ChevronDownIcon } from '@radix-ui/react-icons';
import { Orientation } from 'enumerations/Orientation.enum';
import { Variation } from 'enumerations/Variation.enum';
import { ButtonType, ButtonVariants } from 'enumerations/ButtonStyle.enum';
import { Flex, FlexItem } from 'components/flex/Flex.dev';
import { PromoAnimatedDefault } from 'src/components/promo-animated/PromoAnimatedDefault.dev';
import { PromoAnimatedImageRight } from 'src/components/promo-animated/PromoAnimatedImageRight.dev';
import { Default as Default_9b90c97026bc92ba76660b3daaa6030a6cbd0646 } from 'components/animated-section/AnimatedSection.dev';
import { VideoBase } from 'components/video/Video';
import { Tabs, TabsList, TabsTrigger, TabsContent } from 'components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from 'components/ui/select';
import { Default as Default_5a87dea7e5d774773867b417bc52e56f48fe590a } from 'src/components/multi-promo-tabs/MultiPromoTab.dev';
import { Default as Default_567cb87e41254de18670d2d9e5ed4fb167d328d0 } from 'src/components/multi-promo/MultiPromoItem.dev';
import { LogoItem } from 'src/components/logo-tabs/LogoItem';
import { IconName } from 'enumerations/Icon.enum';
import { Default as Default_740f90ba7832edddf4239d5524af33cda964553d } from 'components/media-section/MediaSection.dev';
import { NavigationMenu, NavigationMenuItem, NavigationMenuList } from 'components/ui/navigation-menu';
import { Default as Default_ca32c3b453732a7bc2de9d40adf797c419944499 } from 'components/logo/Logo.dev';
import { Default as Default_381ac7cc131558422dfbd5e69df870d355e0da5f } from 'components/footer-navigation-callout/FooterNavigationCallout.dev';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from 'components/ui/accordion';
import { useMatchMedia } from '@/hooks/use-match-media';
import client from 'lib/sitecore-client';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { getContainerPlaceholderProps, isContainerPlaceholderEmpty } from 'components/container/container.util';
import { IconPosition } from 'enumerations/IconPosition.enum';
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from 'components/ui/breadcrumb';
import { Avatar, AvatarFallback, AvatarImage } from 'components/ui/avatar';
import { Badge } from 'components/ui/badge';
import { FloatingDock } from 'components/floating-dock/floating-dock.dev';
import { Toaster as Toaster_08933a59d43d48cc7b3e0cac7378e431b0ad4a55 } from 'components/ui/toaster';
import { formatDateInUTC } from '@/utils/date-utils';
import { AccordionBlockDefault } from 'src/components/accordion-block/AccordionBlockDefault.dev';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'useRef', value: useRef },
      { name: 'useCallback', value: useCallback },
      { name: 'useId', value: useId },
      { name: 'Fragment', value: Fragment },
      { name: 'default', value: React },
      { name: '*', value: React_7214d18997ee864dd178de7b3a8430f6783e8b89 },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'useSitecore', value: useSitecore },
      { name: 'Text', value: Text },
      { name: 'Link', value: Link },
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'Image', value: Image },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'DateField', value: DateField },
    ]
  },
  {
    module: 'src/components/video/VideoPlayer.dev',
    exports: [
      { name: 'VideoPlayer', value: VideoPlayer },
    ]
  },
  {
    module: 'src/components/video/VideoModal.dev',
    exports: [
      { name: 'VideoModal', value: VideoModal },
    ]
  },
  {
    module: 'src/hooks/useVideoModal',
    exports: [
      { name: 'useVideoModal', value: useVideoModal },
    ]
  },
  {
    module: '@/contexts/VideoContext',
    exports: [
      { name: 'useVideo', value: useVideo },
    ]
  },
  {
    module: 'components/icon/Icon',
    exports: [
      { name: 'Default', value: Default },
    ]
  },
  {
    module: 'src/components/image/ImageWrapper.dev',
    exports: [
      { name: 'Default', value: Default_e49b8b0315b5c2e1dfc6d29366b41ef250099b77 },
    ]
  },
  {
    module: 'framer-motion',
    exports: [
      { name: 'motion', value: motion },
      { name: 'AnimatePresence', value: AnimatePresence },
    ]
  },
  {
    module: '@/utils/isMobile',
    exports: [
      { name: 'isMobile', value: isMobile },
    ]
  },
  {
    module: '@/utils/video',
    exports: [
      { name: 'extractVideoId', value: extractVideoId },
    ]
  },
  {
    module: '@/utils/NoDataFallback',
    exports: [
      { name: 'NoDataFallback', value: NoDataFallback },
    ]
  },
  {
    module: 'lib/utils',
    exports: [
      { name: 'cn', value: cn },
      { name: 'getYouTubeThumbnail', value: getYouTubeThumbnail },
    ]
  },
  {
    module: 'components/image/ImageWrapper.dev',
    exports: [
      { name: 'Default', value: Default_2136db61e8a24a8a1d9ace0ce9528745ef345ee3 },
    ]
  },
  {
    module: 'components/button-component/ButtonComponent',
    exports: [
      { name: 'EditableButton', value: EditableButton },
      { name: 'EditableImageButton', value: EditableImageButton },
    ]
  },
  {
    module: '@radix-ui/react-tooltip',
    exports: [
      { name: '*', value: TooltipPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-toggle',
    exports: [
      { name: '*', value: TogglePrimitive },
    ]
  },
  {
    module: 'class-variance-authority',
    exports: [
      { name: 'cva', value: cva },
    ]
  },
  {
    module: '@radix-ui/react-toggle-group',
    exports: [
      { name: '*', value: ToggleGroupPrimitive },
    ]
  },
  {
    module: 'components/ui/toggle',
    exports: [
      { name: 'toggleVariants', value: toggleVariants },
    ]
  },
  {
    module: '@/hooks/use-toast',
    exports: [
      { name: 'useToast', value: useToast },
    ]
  },
  {
    module: 'components/ui/toast',
    exports: [
      { name: 'Toast', value: Toast },
      { name: 'ToastClose', value: ToastClose },
      { name: 'ToastDescription', value: ToastDescription },
      { name: 'ToastProvider', value: ToastProvider },
      { name: 'ToastTitle', value: ToastTitle },
      { name: 'ToastViewport', value: ToastViewport },
    ]
  },
  {
    module: '@radix-ui/react-toast',
    exports: [
      { name: '*', value: ToastPrimitives },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'X', value: X },
      { name: 'PanelLeft', value: PanelLeft },
      { name: 'Check', value: Check },
      { name: 'ChevronDown', value: ChevronDown },
      { name: 'ChevronUp', value: ChevronUp },
      { name: 'GripVertical', value: GripVertical },
      { name: 'Circle', value: Circle },
      { name: 'ChevronLeft', value: ChevronLeft },
      { name: 'ChevronRight', value: ChevronRight },
      { name: 'MoreHorizontal', value: MoreHorizontal },
      { name: 'Dot', value: Dot },
      { name: 'Search', value: Search },
      { name: 'ArrowLeft', value: ArrowLeft },
      { name: 'ArrowRight', value: ArrowRight },
      { name: 'Play', value: Play },
      { name: 'Pause', value: Pause },
      { name: 'Menu', value: Menu },
      { name: 'Facebook', value: Facebook },
      { name: 'Linkedin', value: Linkedin },
      { name: 'Twitter', value: Twitter },
      { name: 'Link', value: Link_6b289e2de0a07a8bed65fcf19e83723e986797b2 },
      { name: 'Mail', value: Mail },
    ]
  },
  {
    module: '@radix-ui/react-tabs',
    exports: [
      { name: '*', value: TabsPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-switch',
    exports: [
      { name: '*', value: SwitchPrimitives },
    ]
  },
  {
    module: 'next-themes',
    exports: [
      { name: 'useTheme', value: useTheme },
    ]
  },
  {
    module: 'sonner',
    exports: [
      { name: 'Toaster', value: Toaster },
    ]
  },
  {
    module: '@radix-ui/react-slider',
    exports: [
      { name: '*', value: SliderPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-slot',
    exports: [
      { name: 'Slot', value: Slot },
    ]
  },
  {
    module: '@/hooks/use-mobile',
    exports: [
      { name: 'useIsMobile', value: useIsMobile },
    ]
  },
  {
    module: 'components/ui/button',
    exports: [
      { name: 'Button', value: Button },
      { name: 'buttonVariants', value: buttonVariants },
    ]
  },
  {
    module: 'components/ui/input',
    exports: [
      { name: 'Input', value: Input },
    ]
  },
  {
    module: 'components/ui/separator',
    exports: [
      { name: 'Separator', value: Separator },
    ]
  },
  {
    module: 'components/ui/sheet',
    exports: [
      { name: 'Sheet', value: Sheet },
      { name: 'SheetContent', value: SheetContent },
      { name: 'SheetTrigger', value: SheetTrigger },
    ]
  },
  {
    module: 'components/ui/skeleton',
    exports: [
      { name: 'Skeleton', value: Skeleton },
    ]
  },
  {
    module: 'components/ui/tooltip',
    exports: [
      { name: 'Tooltip', value: Tooltip },
      { name: 'TooltipContent', value: TooltipContent },
      { name: 'TooltipProvider', value: TooltipProvider },
      { name: 'TooltipTrigger', value: TooltipTrigger },
    ]
  },
  {
    module: '@radix-ui/react-dialog',
    exports: [
      { name: '*', value: SheetPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-separator',
    exports: [
      { name: '*', value: SeparatorPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-select',
    exports: [
      { name: '*', value: SelectPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-scroll-area',
    exports: [
      { name: '*', value: ScrollAreaPrimitive },
    ]
  },
  {
    module: 'react-resizable-panels',
    exports: [
      { name: '*', value: ResizablePrimitive },
    ]
  },
  {
    module: '@radix-ui/react-radio-group',
    exports: [
      { name: '*', value: RadioGroupPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-progress',
    exports: [
      { name: '*', value: ProgressPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-popover',
    exports: [
      { name: '*', value: PopoverPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-navigation-menu',
    exports: [
      { name: '*', value: NavigationMenuPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-menubar',
    exports: [
      { name: '*', value: MenubarPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-label',
    exports: [
      { name: '*', value: LabelPrimitive },
    ]
  },
  {
    module: 'input-otp',
    exports: [
      { name: 'OTPInput', value: OTPInput },
      { name: 'OTPInputContext', value: OTPInputContext },
    ]
  },
  {
    module: '@radix-ui/react-hover-card',
    exports: [
      { name: '*', value: HoverCardPrimitive },
    ]
  },
  {
    module: 'react-hook-form',
    exports: [
      { name: 'Controller', value: Controller },
      { name: 'FormProvider', value: FormProvider },
      { name: 'useFormContext', value: useFormContext },
      { name: 'useForm', value: useForm },
    ]
  },
  {
    module: 'components/ui/label',
    exports: [
      { name: 'Label', value: Label },
    ]
  },
  {
    module: '@radix-ui/react-dropdown-menu',
    exports: [
      { name: '*', value: DropdownMenuPrimitive },
    ]
  },
  {
    module: 'vaul',
    exports: [
      { name: 'Drawer', value: Drawer },
    ]
  },
  {
    module: '@radix-ui/react-context-menu',
    exports: [
      { name: '*', value: ContextMenuPrimitive },
    ]
  },
  {
    module: 'cmdk',
    exports: [
      { name: 'Command', value: Command },
    ]
  },
  {
    module: 'components/ui/dialog',
    exports: [
      { name: 'Dialog', value: Dialog },
      { name: 'DialogContent', value: DialogContent },
    ]
  },
  {
    module: '@radix-ui/react-collapsible',
    exports: [
      { name: '*', value: CollapsiblePrimitive },
    ]
  },
  {
    module: '@radix-ui/react-checkbox',
    exports: [
      { name: '*', value: CheckboxPrimitive },
    ]
  },
  {
    module: 'recharts',
    exports: [
      { name: '*', value: RechartsPrimitive },
    ]
  },
  {
    module: 'embla-carousel-react',
    exports: [
      { name: 'default', value: useEmblaCarousel },
    ]
  },
  {
    module: 'react-day-picker',
    exports: [
      { name: 'DayPicker', value: DayPicker },
    ]
  },
  {
    module: '@radix-ui/react-avatar',
    exports: [
      { name: '*', value: AvatarPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-aspect-ratio',
    exports: [
      { name: '*', value: AspectRatioPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-alert-dialog',
    exports: [
      { name: '*', value: AlertDialogPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-accordion',
    exports: [
      { name: '*', value: AccordionPrimitive },
    ]
  },
  {
    module: 'components/magicui/meteors',
    exports: [
      { name: 'Meteors', value: Meteors },
    ]
  },
  {
    module: 'src/components/topic-listing/TopicItem.dev',
    exports: [
      { name: 'TopicItem', value: TopicItem },
    ]
  },
  {
    module: 'src/components/text-banner/TextBannerDefault.dev',
    exports: [
      { name: 'Default', value: Default_9c943e7f61c2c6a8bdaf3a4e8f1aeba5a19a6639 },
    ]
  },
  {
    module: 'src/components/text-banner/TextBanner01.dev',
    exports: [
      { name: 'Default', value: Default_b7b9c2d49612cce49665fcafdf4020a775dae9a6 },
    ]
  },
  {
    module: 'src/components/text-banner/TextBanner02.dev',
    exports: [
      { name: 'Default', value: Default_d90c163300dcab5740e1badcbbe8ffad62e34ea5 },
    ]
  },
  {
    module: 'radash',
    exports: [
      { name: 'debounce', value: debounce },
    ]
  },
  {
    module: 'components/ui/carousel',
    exports: [
      { name: 'Carousel', value: Carousel },
      { name: 'CarouselContent', value: CarouselContent },
      { name: 'CarouselItem', value: CarouselItem },
      { name: 'CarouselNext', value: CarouselNext },
      { name: 'CarouselPrevious', value: CarouselPrevious },
    ]
  },
  {
    module: 'src/components/testimonial-carousel/TestimonialCarouselItem',
    exports: [
      { name: 'Default', value: Default_f14713561e7127543a30e797b8ea6464ba634f1f },
    ]
  },
  {
    module: 'components/ui/form',
    exports: [
      { name: 'Form', value: Form },
      { name: 'FormControl', value: FormControl },
      { name: 'FormField', value: FormField },
      { name: 'FormItem', value: FormItem },
      { name: 'FormMessage', value: FormMessage },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: '@/variables/dictionary',
    exports: [
      { name: 'dictionaryKeys', value: dictionaryKeys },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: NextLink },
    ]
  },
  {
    module: '@radix-ui/react-icons',
    exports: [
      { name: 'ChevronDownIcon', value: ChevronDownIcon },
    ]
  },
  {
    module: 'enumerations/Orientation.enum',
    exports: [
      { name: 'Orientation', value: Orientation },
    ]
  },
  {
    module: 'enumerations/Variation.enum',
    exports: [
      { name: 'Variation', value: Variation },
    ]
  },
  {
    module: 'enumerations/ButtonStyle.enum',
    exports: [
      { name: 'ButtonType', value: ButtonType },
      { name: 'ButtonVariants', value: ButtonVariants },
    ]
  },
  {
    module: 'components/flex/Flex.dev',
    exports: [
      { name: 'Flex', value: Flex },
      { name: 'FlexItem', value: FlexItem },
    ]
  },
  {
    module: 'src/components/promo-animated/PromoAnimatedDefault.dev',
    exports: [
      { name: 'PromoAnimatedDefault', value: PromoAnimatedDefault },
    ]
  },
  {
    module: 'src/components/promo-animated/PromoAnimatedImageRight.dev',
    exports: [
      { name: 'PromoAnimatedImageRight', value: PromoAnimatedImageRight },
    ]
  },
  {
    module: 'components/animated-section/AnimatedSection.dev',
    exports: [
      { name: 'Default', value: Default_9b90c97026bc92ba76660b3daaa6030a6cbd0646 },
    ]
  },
  {
    module: 'components/video/Video',
    exports: [
      { name: 'VideoBase', value: VideoBase },
    ]
  },
  {
    module: 'components/ui/tabs',
    exports: [
      { name: 'Tabs', value: Tabs },
      { name: 'TabsList', value: TabsList },
      { name: 'TabsTrigger', value: TabsTrigger },
      { name: 'TabsContent', value: TabsContent },
    ]
  },
  {
    module: 'components/ui/select',
    exports: [
      { name: 'Select', value: Select },
      { name: 'SelectContent', value: SelectContent },
      { name: 'SelectItem', value: SelectItem },
      { name: 'SelectTrigger', value: SelectTrigger },
      { name: 'SelectValue', value: SelectValue },
    ]
  },
  {
    module: 'src/components/multi-promo-tabs/MultiPromoTab.dev',
    exports: [
      { name: 'Default', value: Default_5a87dea7e5d774773867b417bc52e56f48fe590a },
    ]
  },
  {
    module: 'src/components/multi-promo/MultiPromoItem.dev',
    exports: [
      { name: 'Default', value: Default_567cb87e41254de18670d2d9e5ed4fb167d328d0 },
    ]
  },
  {
    module: 'src/components/logo-tabs/LogoItem',
    exports: [
      { name: 'LogoItem', value: LogoItem },
    ]
  },
  {
    module: 'enumerations/Icon.enum',
    exports: [
      { name: 'IconName', value: IconName },
    ]
  },
  {
    module: 'components/media-section/MediaSection.dev',
    exports: [
      { name: 'Default', value: Default_740f90ba7832edddf4239d5524af33cda964553d },
    ]
  },
  {
    module: 'components/ui/navigation-menu',
    exports: [
      { name: 'NavigationMenu', value: NavigationMenu },
      { name: 'NavigationMenuItem', value: NavigationMenuItem },
      { name: 'NavigationMenuList', value: NavigationMenuList },
    ]
  },
  {
    module: 'components/logo/Logo.dev',
    exports: [
      { name: 'Default', value: Default_ca32c3b453732a7bc2de9d40adf797c419944499 },
    ]
  },
  {
    module: 'components/footer-navigation-callout/FooterNavigationCallout.dev',
    exports: [
      { name: 'Default', value: Default_381ac7cc131558422dfbd5e69df870d355e0da5f },
    ]
  },
  {
    module: 'components/ui/accordion',
    exports: [
      { name: 'Accordion', value: Accordion },
      { name: 'AccordionContent', value: AccordionContent },
      { name: 'AccordionItem', value: AccordionItem },
      { name: 'AccordionTrigger', value: AccordionTrigger },
    ]
  },
  {
    module: '@/hooks/use-match-media',
    exports: [
      { name: 'useMatchMedia', value: useMatchMedia },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'components/container/container.util',
    exports: [
      { name: 'getContainerPlaceholderProps', value: getContainerPlaceholderProps },
      { name: 'isContainerPlaceholderEmpty', value: isContainerPlaceholderEmpty },
    ]
  },
  {
    module: 'enumerations/IconPosition.enum',
    exports: [
      { name: 'IconPosition', value: IconPosition },
    ]
  },
  {
    module: 'components/ui/breadcrumb',
    exports: [
      { name: 'Breadcrumb', value: Breadcrumb },
      { name: 'BreadcrumbItem', value: BreadcrumbItem },
      { name: 'BreadcrumbLink', value: BreadcrumbLink },
      { name: 'BreadcrumbList', value: BreadcrumbList },
      { name: 'BreadcrumbPage', value: BreadcrumbPage },
      { name: 'BreadcrumbSeparator', value: BreadcrumbSeparator },
    ]
  },
  {
    module: 'components/ui/avatar',
    exports: [
      { name: 'Avatar', value: Avatar },
      { name: 'AvatarFallback', value: AvatarFallback },
      { name: 'AvatarImage', value: AvatarImage },
    ]
  },
  {
    module: 'components/ui/badge',
    exports: [
      { name: 'Badge', value: Badge },
    ]
  },
  {
    module: 'components/floating-dock/floating-dock.dev',
    exports: [
      { name: 'FloatingDock', value: FloatingDock },
    ]
  },
  {
    module: 'components/ui/toaster',
    exports: [
      { name: 'Toaster', value: Toaster_08933a59d43d48cc7b3e0cac7378e431b0ad4a55 },
    ]
  },
  {
    module: '@/utils/date-utils',
    exports: [
      { name: 'formatDateInUTC', value: formatDateInUTC },
    ]
  },
  {
    module: 'src/components/accordion-block/AccordionBlockDefault.dev',
    exports: [
      { name: 'AccordionBlockDefault', value: AccordionBlockDefault },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
